Relevant Information:
            age     -   age
            bp      -   blood pressure
            sg      -   specific gravity
            al      -   albumin
            su      -   sugar
            rbc     -   red blood cells
            pc      -   pus cell
            pcc     -   pus cell clumps
            ba      -   bacteria
            bgr     -   blood glucose random
            bu      -   blood urea
            sc      -   serum creatinine
            sod     -   sodium
            pot     -   potassium
            hemo        -   hemoglobin
            pcv     -   packed cell volume
            wc      -   white blood cell count
            rc      -   red blood cell count
            htn     -   hypertension
            dm      -   diabetes mellitus
            cad     -   coronary artery disease
            appet       -   appetite
            pe      -   pedal edema
            ane     -   anemia
            class       -   class   

4.Number of Instances: 400 (250 CKD, 150 notckd)

5.Number of Attributes: 24 + class = 25 ( 11 numeric ,14 nominal)


6.Attribute Information :
    1.Age(numerical)
        age in years
    2.Blood Pressure(numerical)
            bp in mm/Hg
    3.Specific Gravity(nominal)
        sg - (1.005,1.010,1.015,1.020,1.025)
    4.Albumin(nominal)
        al - (0,1,2,3,4,5)
    5.Sugar(nominal)
        su - (0,1,2,3,4,5)
    6.Red Blood Cells(nominal)
        rbc - (normal,abnormal)
    7.Pus Cell (nominal)
        pc - (normal,abnormal)
    8.Pus Cell clumps(nominal)
        pcc - (present,notpresent)
    9.Bacteria(nominal)
        ba  - (present,notpresent)
    10.Blood Glucose Random(numerical)      
        bgr in mgs/dl
    11.Blood Urea(numerical)    
        bu in mgs/dl
    12.Serum Creatinine(numerical)  
        sc in mgs/dl
    13.Sodium(numerical)
        sod in mEq/L
    14.Potassium(numerical) 
        pot in mEq/L
    15.Hemoglobin(numerical)
        hemo in gms
    16.Packed  Cell Volume(numerical)
    17.White Blood Cell Count(numerical)
        wc in cells/cumm
    18.Red Blood Cell Count(numerical)  
        rc in millions/cmm
    19.Hypertension(nominal)    
        htn - (yes,no)
    20.Diabetes Mellitus(nominal)   
        dm - (yes,no)
    21.Coronary Artery Disease(nominal)
        cad - (yes,no)
    22.Appetite(nominal)    
        appet - (good,poor)
    23.Pedal Edema(nominal)
        pe - (yes,no)   
    24.Anemia(nominal)
        ane - (yes,no)
    25.Class (nominal)      
        class - (ckd,notckd)

Missing Attribute Values: Yes(Denoted by "?")

Class Distribution: ( 2 classes)

     Class     Number of instances
     ckd               250
     notckd            150

In [2]:
#importing libraries
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
%matplotlib inline
from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
from sklearn.feature_selection import RFECV,SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR, SVC, LinearSVC
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB

In [3]:
df = pd.read_csv(r'C:\Users\O92929\Desktop\CKD dataset.csv')

In [4]:
df.head(10)

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
0,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
1,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
2,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
3,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
4,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,39.0,7800.0,4.4,yes,yes,no,good,yes,no,ckd
5,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,...,36.0,NaN,NaN,no,no,no,good,no,no,ckd
6,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,...,44.0,6900.0,5.0,no,yes,no,good,yes,no,ckd
7,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,...,33.0,9600.0,4.0,yes,yes,no,good,no,yes,ckd
8,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29.0,12100.0,3.7,yes,yes,no,poor,no,yes,ckd
9,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,...,28.0,NaN,NaN,yes,yes,no,good,no,yes,ckd

In [5]:
CKD_df = df.copy()

In [6]:
CKD_df.head()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
0,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
1,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
2,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
3,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
4,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,39.0,7800.0,4.4,yes,yes,no,good,yes,no,ckd

In [9]:
CKD_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     391 non-null    float64
 1   Bloodpressure           388 non-null    float64
 2   Specific Gravity        353 non-null    float64
 3   Albumin                 351 non-null    float64
 4   Sugar                   351 non-null    float64
 5   RBC                     248 non-null    object
 6   Pus Cell                335 non-null    object
 7   Pus Cell Clumps         396 non-null    object
 8   Bacteria                396 non-null    object
 9   Blood Glucose Random    356 non-null    float64
 10  Blood Urea              381 non-null    float64
 11  Serum Creatine          383 non-null    float64
 12  Sodium                  313 non-null    float64
 13  Potassium               312 non-null    float64
 14  Hemoglobin              348 non-null    float64
 15  Packed Cell Volume      329 non-null    float64
 16  White Blood Cell Count  294 non-null    float64
 17  Red Blood Cell Count    269 non-null    float64
 18  Hypertension            400 non-null    object
 19  Diabetes Mellitus       400 non-null    object
 20  Coronary Artery         400 non-null    object
 21  Appetite                400 non-null    object
 22  Pedal Edema             400 non-null    object
 23  Anemeia                 400 non-null    object
 24  Class                   399 non-null    object
dtypes: float64(14), object(11)
memory usage: 61.0+ KB

In [10]:
CKD_df.shape

(400, 25)

In [13]:
CKD_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,391.0,51.462916,17.178640,2.000,42.00,55.00,64.50,90.000
Bloodpressure,388.0,76.469072,13.683637,50.000,70.00,80.00,80.00,180.000
Specific Gravity,353.0,1.017408,0.005717,1.005,1.01,1.02,1.02,1.025
Albumin,351.0,1.014245,1.353228,0.000,0.00,0.00,2.00,5.000
Sugar,351.0,0.450142,1.099191,0.000,0.00,0.00,0.00,5.000
Blood Glucose Random,356.0,148.036517,79.281714,22.000,99.00,121.00,163.00,490.000
Blood Urea,381.0,57.425722,50.503006,1.500,27.00,42.00,66.00,391.000
Serum Creatine,383.0,3.072454,5.741126,0.400,0.90,1.30,2.80,76.000
Sodium,313.0,137.528754,10.408752,4.500,135.00,138.00,142.00,163.000
Potassium,312.0,4.627244,3.193904,2.500,3.80,4.40,4.90,47.000
Hemoglobin,348.0,12.526437,2.912587,3.100,10.30,12.65,15.00,17.800
Packed Cell Volume,329.0,38.884498,8.990105,9.000,32.00,40.00,45.00,54.000
White Blood Cell Count,294.0,8406.122449,2944.474190,2200.000,6500.00,8000.00,9800.00,26400.000
Red Blood Cell Count,269.0,4.707435,1.025323,2.100,3.90,4.80,5.40,8.000

In [15]:
CKD_df.columns

Index(['Age', 'Bloodpressure', 'Specific Gravity', 'Albumin', 'Sugar', 'RBC',
       'Pus Cell', 'Pus Cell Clumps', 'Bacteria', 'Blood Glucose Random',
       'Blood Urea', 'Serum Creatine', 'Sodium', 'Potassium', 'Hemoglobin',
       'Packed Cell Volume', 'White Blood Cell Count', 'Red Blood Cell Count',
       'Hypertension', 'Diabetes Mellitus', 'Coronary Artery', 'Appetite',
       'Pedal Edema', 'Anemeia', 'Class'],
      dtype='object')

In [18]:
CKD_df.dropna()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
2,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
8,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29.0,12100.0,3.7,yes,yes,no,poor,no,yes,ckd
10,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,32.0,4500.0,3.8,yes,yes,no,poor,yes,no,ckd
13,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,16.0,11000.0,2.6,yes,yes,yes,poor,yes,no,ckd
19,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,24.0,9200.0,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
395,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
396,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
397,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
398,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [17]:
CKD_df1.dropna()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
2,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
8,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,...,29.0,12100.0,3.7,yes,yes,no,poor,no,yes,ckd
10,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,...,32.0,4500.0,3.8,yes,yes,no,poor,yes,no,ckd
13,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,...,16.0,11000.0,2.6,yes,yes,yes,poor,yes,no,ckd
19,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,...,24.0,9200.0,3.2,yes,yes,yes,poor,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47.0,6700.0,4.9,no,no,no,good,no,no,notckd
395,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.0,7800.0,6.2,no,no,no,good,no,no,notckd
396,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.0,6600.0,5.4,no,no,no,good,no,no,notckd
397,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.0,7200.0,5.9,no,no,no,good,no,no,notckd
398,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53.0,6800.0,6.1,no,no,no,good,no,no,notckd

In [19]:
replacements = {
    'poor' : 0.0,
    'good' : 1.0,
    'normal' : 1.0,
    'abnormal' : 0.0,
    'notpresent' : 0.0,
    'present' : 1.0,
    'yes' : 1.0,
    'no' : 0.0,
    'ckd' : 1.0,
    'notckd' : 0.0
}
CKD_df = CKD_df.replace(replacements)

In [20]:
CKD_df.head()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
0,7.0,50.0,1.020,4.0,0.0,NaN,1.0,0.0,0.0,NaN,...,38.0,6000.0,NaN,0,0,0,1,0,0,1.0
1,62.0,80.0,1.010,2.0,3.0,1.0,1.0,0.0,0.0,423.0,...,31.0,7500.0,NaN,0,1,0,0,0,1,1.0
2,48.0,70.0,1.005,4.0,0.0,1.0,0.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1,0,0,0,1,1,1.0
3,51.0,80.0,1.010,2.0,0.0,1.0,1.0,0.0,0.0,106.0,...,35.0,7300.0,4.6,0,0,0,1,0,0,1.0
4,60.0,90.0,1.015,3.0,0.0,NaN,NaN,0.0,0.0,74.0,...,39.0,7800.0,4.4,1,1,0,1,1,0,1.0

In [21]:
df.head()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
0,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
1,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
2,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
3,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd
4,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,...,39.0,7800.0,4.4,yes,yes,no,good,yes,no,ckd

In [22]:
df.shape

(400, 25)

In [23]:
CKD_df.shape

(400, 25)

In [24]:
CKD_df

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
0,7.0,50.0,1.020,4.0,0.0,NaN,1.0,0.0,0.0,NaN,...,38.0,6000.0,NaN,0,0,0,1,0,0,1.0
1,62.0,80.0,1.010,2.0,3.0,1.0,1.0,0.0,0.0,423.0,...,31.0,7500.0,NaN,0,1,0,0,0,1,1.0
2,48.0,70.0,1.005,4.0,0.0,1.0,0.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1,0,0,0,1,1,1.0
3,51.0,80.0,1.010,2.0,0.0,1.0,1.0,0.0,0.0,106.0,...,35.0,7300.0,4.6,0,0,0,1,0,0,1.0
4,60.0,90.0,1.015,3.0,0.0,NaN,NaN,0.0,0.0,74.0,...,39.0,7800.0,4.4,1,1,0,1,1,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,42.0,70.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,75.0,...,54.0,7800.0,6.2,0,0,0,1,0,0,0.0
396,12.0,80.0,1.020,0.0,0.0,1.0,1.0,0.0,0.0,100.0,...,49.0,6600.0,5.4,0,0,0,1,0,0,0.0
397,17.0,60.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,114.0,...,51.0,7200.0,5.9,0,0,0,1,0,0,0.0
398,58.0,80.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,131.0,...,53.0,6800.0,6.1,0,0,0,1,0,0,0.0
399,40.0,80.0,1.020,1.0,0.0,NaN,1.0,0.0,0.0,121.0,...,44.0,7800.0,5.2,1,1,0,1,0,0,NaN

In [25]:
CKD_df.dropna()

,Age,Bloodpressure,Specific Gravity,Albumin,Sugar,RBC,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose Random,...,Packed Cell Volume,White Blood Cell Count,Red Blood Cell Count,Hypertension,Diabetes Mellitus,Coronary Artery,Appetite,Pedal Edema,Anemeia,Class
2,48.0,70.0,1.005,4.0,0.0,1.0,0.0,1.0,0.0,117.0,...,32.0,6700.0,3.9,1,0,0,0,1,1,1.0
8,53.0,90.0,1.020,2.0,0.0,0.0,0.0,1.0,0.0,70.0,...,29.0,12100.0,3.7,1,1,0,0,0,1,1.0
10,63.0,70.0,1.010,3.0,0.0,0.0,0.0,1.0,0.0,380.0,...,32.0,4500.0,3.8,1,1,0,0,1,0,1.0
13,68.0,80.0,1.010,3.0,2.0,1.0,0.0,1.0,1.0,157.0,...,16.0,11000.0,2.6,1,1,1,0,1,0,1.0
19,61.0,80.0,1.015,2.0,0.0,0.0,0.0,0.0,0.0,173.0,...,24.0,9200.0,3.2,1,1,1,0,1,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,55.0,80.0,1.020,0.0,0.0,1.0,1.0,0.0,0.0,140.0,...,47.0,6700.0,4.9,0,0,0,1,0,0,0.0
395,42.0,70.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,75.0,...,54.0,7800.0,6.2,0,0,0,1,0,0,0.0
396,12.0,80.0,1.020,0.0,0.0,1.0,1.0,0.0,0.0,100.0,...,49.0,6600.0,5.4,0,0,0,1,0,0,0.0
397,17.0,60.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,114.0,...,51.0,7200.0,5.9,0,0,0,1,0,0,0.0
398,58.0,80.0,1.025,0.0,0.0,1.0,1.0,0.0,0.0,131.0,...,53.0,6800.0,6.1,0,0,0,1,0,0,0.0

In [28]:
CKD_df.shape

(161, 25)

In [27]:
CKD_df = CKD_df.dropna()

In [30]:
CKD_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 161 entries, 2 to 398
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     161 non-null    float64
 1   Bloodpressure           161 non-null    float64
 2   Specific Gravity        161 non-null    float64
 3   Albumin                 161 non-null    float64
 4   Sugar                   161 non-null    float64
 5   RBC                     161 non-null    float64
 6   Pus Cell                161 non-null    float64
 7   Pus Cell Clumps         161 non-null    float64
 8   Bacteria                161 non-null    float64
 9   Blood Glucose Random    161 non-null    float64
 10  Blood Urea              161 non-null    float64
 11  Serum Creatine          161 non-null    float64
 12  Sodium                  161 non-null    float64
 13  Potassium               161 non-null    float64
 14  Hemoglobin              161 non-null    float64
 15  Packed Cell Volume      161 non-null    float64
 16  White Blood Cell Count  161 non-null    float64
 17  Red Blood Cell Count    161 non-null    float64
 18  Hypertension            161 non-null    object
 19  Diabetes Mellitus       161 non-null    object
 20  Coronary Artery         161 non-null    object
 21  Appetite                161 non-null    object
 22  Pedal Edema             161 non-null    object
 23  Anemeia                 161 non-null    object
 24  Class                   161 non-null    float64
dtypes: float64(19), object(6)
memory usage: 28.9+ KB

In [53]:
import numpy as np

CKD_df = CKD_df.replace("", "0")

In [54]:
CKD_df = CKD_df.dropna()

In [55]:
X=CKD_df.drop(['Class'], axis=1)
Y=CKD_df['Class']
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.2)
clf = LogisticRegression()
clf = clf.fit(X_train, Y_train)
Y_train_pred = clf.predict(X_train)
Y_test_pred = clf.predict(X_test)

print(clf.score(Y_test_pred,Y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 1. 0. 1. 1. 0. 1.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.